### ISSUE TITLE
Label functionality deviates a lot from Mendix default

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/boolean-slider#10]
In version 1.1 the label was added, in version 2.0.0 it was made translatable. However it's also required now, the Mendix project will simply not build when no label is configured.

It seems that by setting a " " as label and width to 0 no label is displayed, but it would be much more intuitive if the widget would have an option label yes/no and horizontal/vertical as with the default Mendix input widgets.

**Comment by edwinmp** [comment]
Hi @JelleDekker, thanks for raising this. Will have the required label issue fixed asap.
As for the orientation, the switch mirrors the behavior of Mendix input widgets. The orientation is not set on the input itself but on the enclosing data view.

**Comment by JelleDekker** [comment]
@edwinmp thanks for the clarification.

**Comment by edwinmp** [comment]
Hi @JelleDekker, the required label issue has been fixed in version 2.0.1. You can download it from the appstore or from the GitHub [release](https://github.com/mendixlabs/boolean-slider/releases/tag/2.0.1)
