### ISSUE TITLE
Example project shows editable Switch in TemplateGrid, this is however not possible

### ISSUE THREAD

**Issue by JelleDekker** [mendixlabs/boolean-slider#11]
The linked https://booleansliderwidge.mxapps.io/ demo shows editable switches in a templategrid. However this is not possible as the latest version of the switch widget automatically disables in non-editable views (such as template grids).

**Comment by edwinmp** [comment]
Hi @JelleDekker. The demo project has been updated with the latest version of the widget (v2.0.1)
