### ISSUE TITLE
allow onchange settings for microflow execution

### ISSUE THREAD

**Issue by snuman** [mendixlabs/boolean-slider#13]
option to call onchange microflow to be called synchronous or asynchronous with a blocking or non-blocking progress message.

Like the 'default' on change options through the modeler.

**Comment by edwinmp** [comment]
Hi @snuman, that's an excellent suggestion. Unfortunately, we won't be able to include that feature anytime soon, but it has been added to the backlog for possible inclusion in a later release.

**Comment by Andries-Smit** [comment]
When converting this widget to pluggable widget this feature will be available. No timeline can be given for the availability.
