### ISSUE TITLE
Unnecessary class "form-horizontal" in the slider

### ISSUE THREAD

**Issue by deronnie** [mendixlabs/boolean-slider#14]
in this file "boolean-slider/src/components/Label.ts" is the class 'form-horizontal' hard coded in the slider element. 

This class comes with the form where you will use the slider, so it should not be in this element.
Also, this tends to break the element on vertical showing forms as seen on this image: 
![image](https://user-images.githubusercontent.com/18141655/35332218-8789eaf0-010a-11e8-87cd-69e73291470a.png)

This easy and quick fix makes the slider even more usefull ;)

**Comment by edwinmp** [comment]
Hi @deronnie, thanks for raising this. It has been addressed in the next release. Will let u know when it's been published.

**Comment by deronnie** [comment]
Yes!  thanks!

Van: Edwin P. Magezi [mailto:notifications@github.com]
Verzonden: woensdag 24 januari 2018 13:35
Aan: mendixlabs/boolean-slider <boolean-slider@noreply.github.com>
CC: Doorn, Ronnie van <ronnie.van.doorn@enexis.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mendixlabs/boolean-slider] Unnecessary class "form-horizontal" in the slider (#14)


Hi @deronnie<https://github.com/deronnie>, thanks for raising this. It has been addressed in the next release. Will let u know when it's been published.

**Comment by Andries-Smit** [comment]
Dear Ronnie

The requested change is applied and release https://appstore.home.mendix.com/link/app/50324/ version 2.0.2

Please let u know if this solves your problem.

Cheers, Andries
