### ISSUE TITLE
True / False labels

### ISSUE THREAD

**Issue by Mcpoowl** [mendixlabs/boolean-slider#18]
It would be great if the Switch widget would support true / false text labels which show up IN the switch, as with the old boolean slider widget.

See image: 
![image009](https://user-images.githubusercontent.com/2244753/40773263-a1016532-64c2-11e8-9402-556ef6ff0132.png)

**Comment by Andries-Smit** [comment]
Thanks for placing the request, it seems like a valid request.
We will discuss it with the product owner.

**Comment by Andries-Smit** [comment]
Sorry we will not add this feature to this widget.
