### ISSUE TITLE
I would like to have the option to hide the label and the option to make the label align vertically with the toggle.

### ISSUE THREAD

**Issue by mrgroen** [mendixlabs/boolean-slider#23]
The label and toggle are forced into horizontal bootstrap grid system containers. This is conflicting with my form styling in Mendix. I would like to have the option to hide/remove the label. And I would like to align the label vertically with the toggle.

**Comment by Andries-Smit** [comment]
We wont fix this for now, We are converting this widget into a pluggable widget, the will use the standard label component, making your request supported. For now you can use CSS to remove it from the DOM.
